version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum"  }}
      - run:
          name: "Test with GoTestSum"
          command: |
            mkdir ./test-output
            gotestsum --junitfile ./test-output/unit-tests.xml
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum"  }}
          paths:
            - /home/circleci/go/pkg/mod
      - store_test_results:
          path: ./test-output
      - run:
          name: "Try compiling"
          command: go build ./...
