version: 2.1

orbs:
  gor: hubci/goreleaser@2.3
  codecov: codecov/codecov@3.2

workflows:
  main-wf:
    jobs:
      - test
      - gor/release:
          name: goreleaser-snapshot
          version: "1.17.2"
          go-version: "1.20.3"
          dry-run: true
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "dist"
  release-wf:
    jobs:
      - test:
          filters: &semverFilters
            branches:
              ignore: /.*/
            tags:
              # SemVer regex
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - gor/release:
          name: goreleaser-publish
          version: "1.17.2"
          go-version: "1.20.3"
          filters: *semverFilters
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "dist"
          context: goreleaser-ctx

jobs:
  test:
    docker:
      - image: cimg/go:1.20.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: "Download Dependancies"
          command: |
            go mod download
            curl -sSL "https://github.com/magefile/mage/releases/download/v1.14.0/mage_1.14.0_Linux-64bit.tar.gz" | sudo tar -xz --no-same-owner -C /usr/local/bin mage
            mage --version
      - run:
          name: "Test with GoTestSum"
          command: |
            mkdir ./test-output
            gotestsum --junitfile ./test-output/unit-tests.xml
      - store_test_results:
          path: ./test-output
      - store_artifacts:
          path: test-output/unit-tests.xml
      - run:
          name: "Try compiling"
          command: go build ./...
      - codecov/upload
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/.cache/go-build"
